# Generated by Django 5.0.6 on 2024-12-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=75)),
                ('site_logo', models.FileField(upload_to='uploads/site_logo')),
                ('favicon', models.FileField(upload_to='uploads/favicon')),
                ('telegram', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('recent_films_slider_1', models.ManyToManyField(related_name='recent_films', to='movie_app.film')),
                ('recent_series_slider_2', models.ManyToManyField(related_name='recent_series', to='movie_app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('number_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='movie_app.film')),
                ('number_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='movie_app.serie')),
                ('number_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='movie_app.serie')),
                ('number_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='four', to='movie_app.serie')),
                ('number_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='movie_app.film')),
            ],
        ),
    ]
