# Generated by Django 5.0.6 on 2024-12-12 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('length', models.IntegerField()),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='uploads/banners')),
                ('background', models.ImageField(blank=True, null=True, upload_to='uploads/backgrounds')),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='uploads/trailers')),
                ('slug', models.SlugField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.country')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.date')),
                ('genre', models.ManyToManyField(related_name='film_genre', to='movie_app.genre')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='FilmVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.film')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilmByQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/films')),
                ('is_active', models.BooleanField(default=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.film')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_count', models.IntegerField()),
                ('part_avg_length', models.IntegerField()),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/series')),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=50)),
                ('banner', models.FileField(upload_to='uploads/banners')),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='uploads/backgrounds')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='uploads/trailers')),
                ('slug', models.SlugField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.country')),
                ('end_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='movie_app.date')),
                ('genre', models.ManyToManyField(related_name='serie_genre', to='movie_app.genre')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.language')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='movie_app.date')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.serie'),
        ),
        migrations.CreateModel(
            name='SerieVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.serie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
