# Generated by Django 5.0.6 on 2024-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_films',
            field=models.ManyToManyField(blank=True, related_name='saved_series', to='movie_app.film'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_series',
            field=models.ManyToManyField(blank=True, related_name='saved_series', to='movie_app.serie'),
        ),
    ]
